### ISSUE TITLE
The app keeps on crashing 

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1403]
Version: Thai preview 5.3.25
User: raitest 
Login to the app. 
Wait for the sync to complete 
Turn the internet off 
Go to list view
Select an old residential structure(existing)
Click on add new member 
App crashes 

Varshana has also been experiencing some app crashes at the same time. I used Samsung A21, she used Huawei.
@Rkareko we should check Crashylitcs 
![image](https://user-images.githubusercontent.com/61143692/117122458-9a4b5b80-ad9e-11eb-8b1b-07ad1ceac1a9.png)

**Comment by Rkareko** [comment]
some errors from crashlytics [ BaseDrawerPresenter.java line 424 ](https://console.firebase.google.com/u/0/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues/4377470bacac190df9c4adefda0a1df5?time=last-seven-days&sessionEventKey=6092633303270001242343C2A00B4277_1537179705312481744)

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
       at org.smartregister.reveal.presenter.BaseDrawerPresenter.updateSyncStatusDisplay(BaseDrawerPresenter.java:424)
       at org.smartregister.reveal.interactor.BaseDrawerInteractor$3$1.run(BaseDrawerInteractor.java:132)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
