### ISSUE TITLE
App Crashing after you click on 'Allow' to the prompt "Allow Reveal to manage and make phone calls"

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-reveal#1468]
@LZRS please take note of this issue on Thai local
raised under this issue #1464 

-After you login to the app
-When adding a new structure
-and a prompt asking you to "Allow Reveal to manage and make phone calls"
-when you click Allow the app crashes and you have to click on it and login in again...
app version:
5.3.26 (thai local)
android version: 11
user: bvbd_test

I am unable to upload a video here but i have shared it on slack.
![image](https://user-images.githubusercontent.com/84722169/124486673-8203b700-ddb6-11eb-947c-c159aadec243.png)

**Comment by Rkareko** [comment]
@LZRS check whether it's related to [this crash report on crashlytics ](https://console.firebase.google.com/u/0/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues/fc343400f8f2e486915f46653680c778?time=last-seven-days&sessionEventKey=60E7BD2E012F0001441EFF8771BD1E9E_1561217137554192613)

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=15143, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.smartregister.reveal/org.smartregister.reveal.activity.RevealJsonFormActivity}: java.lang.SecurityException: getDeviceId: The user 10260 does not meet the requirements to access device identifiers.
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8173)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
Caused by java.lang.SecurityException: getDeviceId: The user 10260 does not meet the requirements to access device identifiers.
       at android.os.Parcel.createException(Parcel.java:2088)
       at android.os.Parcel.readException(Parcel.java:2056)
       at android.os.Parcel.readException(Parcel.java:2004)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:11195)
       at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:2283)
       at com.vijay.jsonwizard.utils.PropertyManager.getDeviceId(PropertyManager.java:88)
       at com.vijay.jsonwizard.utils.PropertyManager.addPhoneProperties(PropertyManager.java:127)
       at com.vijay.jsonwizard.utils.PropertyManager.access$000(PropertyManager.java:42)
       at com.vijay.jsonwizard.utils.PropertyManager$1.onRequestPermissionResult(PropertyManager.java:110)
       at com.vijay.jsonwizard.activities.JsonFormBaseActivity.onRequestPermissionsResult(JsonFormBaseActivity.java:195)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8482)
       at android.app.Activity.dispatchActivityResult(Activity.java:8304)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8173)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by madrinekariuki** [comment]
@LZRS This is also affecting `nm-prod apk v5.3.26`.

user tested with: user1_nam
OA: Test OA
Plan : Dynamic-IRS 2021-07-02

**Comment by madrinekariuki** [comment]
Tested this on the shared APK 5.3.26-na-stage.apk
user:ams1

Tested on 2 devices. Android 6 and android 11

Noted. 
on both devices when A user is prompted with "Allow this App to make phone calls" on the add a structure menu.
and a user clicks on accept
the app proceeds to take the user to adding a structure without crashing.
