### ISSUE TITLE
Random App Crashing on Thailand v2.6.2

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#579]
The tablet crashes at random times when I leave the tablet sitting idle for some time. 

APK version: 2.6.2 (filename: opensrp-reveal-release-2.6.2-th-en.apk)
user: bvbd_mhealth

There's a sync intent service being called from the togo library that's causing the crash. Below is the logcat:

`
2019-11-21 11:01:36.132 16197-27034/org.smartregister.chw.togo E/JobExecutor: Crashed job{id=3, finished=true, result=FAILURE, canceled=false, periodic=true, class=ImageUploadServiceJob, tag=ImageUploadServiceJob}
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.smartregister.chw.togo/org.smartregister.service.ImageUploadSyncService }: app is in background uid UidRecord{74d52d1 u0a1 TRNB idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at org.smartregister.job.ImageUploadServiceJob.onRunJob(ImageUploadServiceJob.java:20)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-11-21 11:01:36.148 16197-27035/org.smartregister.chw.togo E/JobExecutor: Crashed job{id=4, finished=true, result=FAILURE, canceled=false, periodic=true, class=PullUniqueIdsServiceJob, tag=PullUniqueIdsServiceJob}
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.smartregister.chw.togo/org.smartregister.sync.intent.PullUniqueIdsIntentService }: app is in background uid UidRecord{74d52d1 u0a1 TRNB idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at org.smartregister.job.PullUniqueIdsServiceJob.onRunJob(PullUniqueIdsServiceJob.java:20)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-11-21 11:01:36.162 16197-27034/org.smartregister.chw.togo E/JobExecutor: Crashed job{id=5, finished=true, result=FAILURE, canceled=false, periodic=true, class=ChwIndicatorGeneratingJob, tag=IndicatorGeneratingJob}
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.smartregister.chw.togo/org.smartregister.reporting.service.IndicatorGeneratorIntentService }: app is in background uid UidRecord{74d52d1 u0a1 TRNB idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at org.smartregister.reporting.job.RecurringIndicatorGeneratingJob.onRunJob(RecurringIndicatorGeneratingJob.java:19)
        at org.smartregister.chw.core.job.ChwIndicatorGeneratingJob.onRunJob(ChwIndicatorGeneratingJob.java:10)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-11-21 11:01:36.184 16197-27034/org.smartregister.chw.togo E/JobExecutor: Crashed job{id=1, finished=true, result=FAILURE, canceled=false, periodic=true, class=SyncServiceJob, tag=SyncServiceJob}
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.smartregister.chw.togo/org.smartregister.sync.intent.SyncIntentService }: app is in background uid UidRecord{74d52d1 u0a1 TRNB idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at org.smartregister.job.SyncServiceJob.onRunJob(SyncServiceJob.java:26)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by craigappl** [comment]
This was a problem because I had another app installed on my tablet.
