### ISSUE TITLE
Fix Bugs logged on Crashlytics

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#594]
- [x] Non-fatal Exception: org.json.JSONException No value for type
`Non-fatal Exception: org.json.JSONException: No value for type
       at org.json.JSONObject.get(JSONObject.java:389)
       at org.json.JSONObject.getString(JSONObject.java:550)
       at org.smartregister.util.JsonFormUtils.createEvent(JsonFormUtils.java:181)
       at org.smartregister.family.util.JsonFormUtils.processFamilyUpdateForm(JsonFormUtils.java:153)
       at org.smartregister.family.model.BaseFamilyRegisterModel.processRegistration(BaseFamilyRegisterModel.java:53)
       at org.smartregister.reveal.model.FamilyRegisterModel.processRegistration(FamilyRegisterModel.java:41)
       at org.smartregister.family.presenter.BaseFamilyRegisterPresenter.saveForm(BaseFamilyRegisterPresenter.java:104)
       at org.smartregister.family.activity.BaseFamilyRegisterActivity.onActivityResultExtended(BaseFamilyRegisterActivity.java:71)`

- [x] NPE when opening the family profile
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void org.smartregister.reveal.contract.StructureTasksContract$Presenter.refreshTasks()' on a null object reference
       at org.smartregister.reveal.fragment.StructureTasksFragment.onResume(StructureTasksFragment.java:103)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
```

- [x] Error when creating tasks
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.smartregister.domain.PlanDefinition.getActions()' on a null object reference
       at org.smartregister.reveal.util.TaskUtils.generateTask(TaskUtils.java:73)
       at org.smartregister.reveal.interactor.BaseInteractor$2.run(BaseInteractor.java:317)`

- [x] Error when opening drawer menu
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.DrawerLayout.addDrawerListener(android.support.v4.widget.DrawerLayout$DrawerListener)' on a null object reference
       at org.smartregister.reveal.view.DrawerMenuView.initializeDrawerLayout(DrawerMenuView.java:71)
       at org.smartregister.reveal.fragment.TaskRegisterFragment.onCreate(TaskRegisterFragment.java:80)
```

- [x] Error when setting total tasks
```
Fatal Exception: java.lang.IllegalStateException: Fragment TaskRegisterFragment{7910faf} not attached to a context.
       at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
       at android.support.v4.app.Fragment.getResources(Fragment.java:760)
       at org.smartregister.reveal.fragment.TaskRegisterFragment.setTotalTasks(TaskRegisterFragment.java:182)
       at org.smartregister.reveal.presenter.TaskRegisterFragmentPresenter.onTasksFound(TaskRegisterFragmentPresenter.java:158)
       at org.smartregister.reveal.interactor.TaskRegisterFragmentInteractor.lambda$null$2(TaskRegisterFragmentInteractor.java:324)
       at org.smartregister.reveal.interactor.-$$Lambda$TaskRegisterFragmentInteractor$kJH6ZVSc1oMf9BPNfzIpIhSxuSc.run(lambda)
```

- [x] Error tagging event metadata details
```
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.smartregister.clientandeventmodel.Client org.smartregister.family.domain.FamilyEventClient.getClient()' on a null object reference
       at org.smartregister.reveal.model.FamilyProfileModel.tagEventClientDetails(FamilyProfileModel.java:55)
       at org.smartregister.reveal.model.FamilyProfileModel.processMemberRegistration(FamilyProfileModel.java:35)
       at org.smartregister.family.presenter.BaseFamilyProfilePresenter.saveFamilyMember(BaseFamilyProfilePresenter.java:192)
       at org.smartregister.family.activity.BaseFamilyProfileActivity.onActivityResult(BaseFamilyProfileActivity.java:160)
```

- [x] Error when selecting plans and no Operational area is selected

```
Non-fatal Exception: java.lang.IllegalArgumentException: the bind value at index 1 is null
       at net.sqlcipher.database.SQLiteProgram.bindString(SQLiteProgram.java:252)
       at net.sqlcipher.database.SQLiteQuery.bindString(SQLiteQuery.java:192)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:66)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1898)
       at org.smartregister.repository.PlanDefinitionSearchRepository.findActivePlansByJurisdiction(PlanDefinitionSearchRepository.java:81)
       at org.smartregister.reveal.interactor.BaseDrawerInteractor$1.run(BaseDrawerInteractor.java:40)
```

**Comment by githengi** [comment]
Non-fatal Exception: org.json.JSONException No value for type resolved by https://github.com/OpenSRP/opensrp-client-core/pull/386
