### ISSUE TITLE
Fix app crash during opening of QR code scanner for P2P sync

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#765]
During initiation of P2P sync, the app crashes due to the following error

`Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/vision/Detector$Processor;
       at org.smartregister.p2p.fragment.QRCodeScanningFragment.create()
       at org.smartregister.p2p.activity.P2pModeSelectActivity.showQRCodeScanningFragment(P2pModeSelectActivity.java:334)
       at org.smartregister.p2p.authenticator.SenderConnectionAuthenticator.authenticate(SenderConnectionAuthenticator.java:33)
       at org.smartregister.p2p.presenter.P2PSenderPresenter.performDeviceAuthentication(P2PSenderPresenter.java:359)
       at org.smartregister.p2p.presenter.P2PSenderPresenter.onConnectionAccepted(P2PSenderPresenter.java:415)
       at org.smartregister.p2p.sync.SyncConnectionLifecycleCallback.onConnectionResult(SyncConnectionLifecycleCallback.java:32)
       at com.google.android.gms.internal.nearby.zzbx.onConnectionResult(:17)
       at com.google.android.gms.internal.nearby.zzab.notifyListener(:15)
       at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(:17)
       at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(:5)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by Naima-Bashir** [comment]
This has passed QA
