### ISSUE TITLE
Fix NPE when location sync returns an empty list

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-client-reveal#800]
The following error is thrown when an empty list is returned during location sync

```
06-23 13:07:33.574  6685  7505 D HTTPAgent: response string:  using url https://reveal-zm.smartregister.org/opensrp/rest/location/sync
06-23 13:07:33.575  6685  7505 E LocationServiceHelper: EXCEPTION java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
06-23 13:07:33.575  6685  7505 E LocationServiceHelper: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at org.smartregister.sync.helper.LocationServiceHelper.batchSyncLocationsStructures(LocationServiceHelper.java:116)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at org.smartregister.sync.helper.LocationServiceHelper.syncLocationsStructures(LocationServiceHelper.java:76)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at org.smartregister.sync.helper.LocationServiceHelper.fetchLocationsStructures(LocationServiceHelper.java:197)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at org.smartregister.reveal.sync.LocationTaskIntentService.doSync(LocationTaskIntentService.java:93)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at org.smartregister.reveal.sync.LocationTaskIntentService.onHandleIntent(LocationTaskIntentService.java:59)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at android.os.Handler.dispatchMessage(Handler.java:106)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at android.os.Looper.loop(Looper.java:164)
06-23 13:07:33.575  6685  7505 E LocationServiceHelper:         at android.os.HandlerThread.run(HandlerThread.java:65)
06-23 13:07:33.576  6685  7505 E AndroidRuntime: FATAL EXCEPTION: IntentService[LocationTaskIntentService]
06-23 13:07:33.576  6685  7505 E AndroidRuntime: Process: org.smartregister.reveal, PID: 6685
06-23 13:07:33.576  6685  7505 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at org.smartregister.sync.helper.LocationServiceHelper.syncLocationsStructures(LocationServiceHelper.java:77)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at org.smartregister.sync.helper.LocationServiceHelper.fetchLocationsStructures(LocationServiceHelper.java:197)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at org.smartregister.reveal.sync.LocationTaskIntentService.doSync(LocationTaskIntentService.java:93)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at org.smartregister.reveal.sync.LocationTaskIntentService.onHandleIntent(LocationTaskIntentService.java:59)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-23 13:07:33.576  6685  7505 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by Naima-Bashir** [comment]
How to test: 
That error was logged on firebase crashlytics
As seen here https://console.firebase.google.com/u/0/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues?state=open&time=last-seven-days&type=crash
Test whether it's solved by checking firebase and see whether it's reported on verison 4.2.1
