### ISSUE TITLE
Date conversion throws exception during payload deserialization

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-reveal#841]
This endpoint returns the date in a format that cause a parse exception during deserialisation of the payload

**../opensrp/rest/clientForm?form_identifier=add_structure.json&form_version=1.0.61**

Here's a sample of one such occurrence

 ### 2020-07-15 20:40:40.505 18970-19860/org.smartregister.reveal E/DocumentConfigurationService: com.google.gson.JsonSyntaxException: 26 Jun 2020, 13:55:31
        at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:151)    
### ....
     Caused by: java.text.ParseException: Failed to parse date ["26 Jun 2020, 13:55:31"]: Invalid number: 26 J
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:274)
        at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:149)
        at com.google.gson.DefaultDateTypeAdapter.read(DefaultDateTypeAdapter.java:128) 
        at com.google.gson.DefaultDateTypeAdapter.read(DefaultDateTypeAdapter.java:44) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:932) 
        at com.google.gson.Gson.fromJson(Gson.java:897) 
        at com.google.gson.Gson.fromJson(Gson.java:846) 
        at com.google.gson.Gson.fromJson(Gson.java:817) 
        at org.smartregister.service.DocumentConfigurationService.fetchClientForm(DocumentConfigurationService.java:129) 
        at org.smartregister.service.DocumentConfigurationService.syncClientForms(DocumentConfigurationService.java:102) 
        at org.smartregister.service.DocumentConfigurationService.fetchManifest(DocumentConfigurationService.java:77) 
        at org.smartregister.sync.intent.DocumentConfigurationIntentService.onHandleIntent(DocumentConfigurationIntentService.java:48) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.NumberFormatException: Invalid number: 26 J
        at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(ISO8601Utils.java:318)
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:129)
        at com.google.gson.DefaultDateTypeAdapter.deserializeToDate(DefaultDateTypeAdapter.java:149) 
        at com.google.gson.DefaultDateTypeAdapter.read(DefaultDateTypeAdapter.java:128) 
        at com.google.gson.DefaultDateTypeAdapter.read(DefaultDateTypeAdapter.java:44) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:932) 
        at com.google.gson.Gson.fromJson(Gson.java:897) 
        at com.google.gson.Gson.fromJson(Gson.java:846) 
        at com.google.gson.Gson.fromJson(Gson.java:817) 
        at org.smartregister.service.DocumentConfigurationService.fetchClientForm(DocumentConfigurationService.java:129) 
        at org.smartregister.service.DocumentConfigurationService.syncClientForms(DocumentConfigurationService.java:102) 
        at org.smartregister.service.DocumentConfigurationService.fetchManifest(DocumentConfigurationService.java:77) 
        at org.smartregister.sync.intent.DocumentConfigurationIntentService.onHandleIntent(DocumentConfigurationIntentService.java:48) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ekigamba** [comment]
@ndegwamartin Is this still happening? I can't seem to find such a date format from either or the OpenSRP stage servers.
